### PR TITLE
Add `SystemSQLite` target for future use in caching

### PR DESCRIPTION
**Pull request by MaxDesiatov**
In subsequent PRs I'd like to introduce a SQLite-backed cache for storing hashes of generated artifacts. That will help us in avoiding redundant work and will make generator significantly quicker for re-runs that change only a few arguments.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
Can we vendor amalgamation sqlite.c instead of depending on system library?

**Comment by MaxDesiatov** [comment]
I need to clarify that. But in the meantime we may need to update Linux CI Dockerfiles to preinstall it.

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
