### PR TITLE
Make CoreFoundation headers in resource dir optional for WebAssembly

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Foundation is not integrated with build-script pipeline for WebAssembly yet, and it will be built as a SwiftPM package in the future. This commit makes CoreFoundation headers optional for WebAssembly for those reasons.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
@swift-ci test macOS

**Comment by kateinoigakukun** [comment]
@swift-ci test macOS

**Comment by kateinoigakukun** [comment]
@swift-ci test macOS

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
