### PR TITLE
Update `swift-async-algorithms` to 1.0.0-beta.1

### PR DESCRIPTION
**Pull request by MaxDesiatov**
The new release contained a breaking change renaming `throttle` to `_throttle`.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by euanh** [comment]
The `_throttle` change came in https://github.com/apple/swift-async-algorithms/pull/296.   The discussion there suggests we should watch out for the semantics possibly changing in a future release.

**Review by euanh — APPROVED** [review]

**Comment by euanh** [comment]
Dependency resolution problem on `swift-main`:
```
debug: [DependencyResolver] 'swift-log[everything] 1.5.3..<2.0.0' is satisfied by '[Derivation: swift-log[everything] 1.5.3..<2.0.0 ← {code[everything] 1.0.0, ¬swift-log[everything] 1.5.3..<2.0.0}]', which is caused by '{code[everything] 1.0.0, ¬swift-log[everything] 1.5.3..<2.0.0}'. new incompatibility: '{code[everything] 1.0.0}'
debug: [DependencyResolver] failed to resolve '{code[everything] 1.0.0}'
error: Dependencies could not be resolved because no versions of 'swift-log' match the requirement 1.5.3..<2.0.0 and root depends on 'swift-log' 1.5.3..<2.0.0.
```

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Pull request merged**
