### PR TITLE
Capture sendable Process instance

### PR DESCRIPTION
**Pull request by krzyzanowskim**
Address Sendable warning

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
This will most likely be superseded by https://github.com/apple/swift-sdk-generator/pull/46, where we're using `actor ProcessExecutor` instead of `Process`, and actors are always `Sendable`.

**Comment by euanh** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
IMO we should get #46 over the finish line instead of merging this.

**Comment by MaxDesiatov** [comment]
Closing as superseded by https://github.com/apple/swift-sdk-generator/commit/620383979461c3190e3b9172015d69fb2fda932e.

**Pull request closed without merging**
